"""AI Assistant routes."""

from typing import List

from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session

from app.core.database import get_db
from app.schemas import AIQuery, AIResponse
from app.services.ai_assistant import answer_query

router = APIRouter(prefix="/ai", tags=["AI Assistant"])


@router.post("/query", response_model=AIResponse, summary="Submit a query to the AI Assistant")
def query(payload: AIQuery, db: Session = Depends(get_db)) -> AIResponse:
    """
    Process an AI query using the provided context and return a structured response.
    
    Args:
        payload (AIQuery): The query payload containing the user's question.
        db (Session): The database session dependency.
        
    Returns:
        AIResponse: The answer generated by the AI assistant.
    """
    return answer_query(db, payload.query)


@router.get("/suggestions", response_model=List[str], summary="Get sample queries")
def suggestions() -> List[str]:
    """
    Return sample queries users can try with the AI Assistant.
    
    Returns:
        List[str]: A list of suggested query strings.
    """
    return [
        "How many available seats are there on Floor 2?",
        "Show me all new joiners without a seat",
        "What is the floor-wise utilization?",
        "How many employees are in project ATLAS?",
        "Where does employee ETH0001 sit?",
        "Show me the project distribution",
        "Give me an overall summary of seat utilization",
        "Which floors have the most available seats?",
    ]
